version: "3.8"

services:
  chess-fen-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chess-fen-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
